### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by stebru** [dzannotti/react-native-thesidebar#6]
How are you supposed to add this to an existing project? I tried the following:

```npm install --save dzannotti/react-thesidebar```

But after doing this, my app stopped running, and I got the following error:
```
TypeError: undefined is not an object (evaluating 'RCTScrollViewConsts.KeyboardDismissMode.None')]
  line: 26061,
  column: 47,
  sourceURL: 'http://localhost:8081/index.ios.bundle'
```
which is reported here: https://github.com/facebook/react-native/issues/2965
So I tried deleting node_modules and running npm install again, but I still get the same error.

Removed react-thesidebar from my project, and my app is up and running again.

**Comment by dzannotti** [comment]
@stebru i apologise for the slow reply, I have just released a pure JS implementation of FB and AirBnB style and published it on npm i hope this fits your needs
