### ISSUE TITLE
I really like this, but can't get it working

### ISSUE THREAD

**Issue by faceyspacey** [dzannotti/react-native-thesidebar#8]
I don't suppose there's an updated version in the works for the latest React Native?

I'm getting this error by the way:

`Class SidebarMainViewManager was not exported. Did you forget to use RCT_EXPORT_MODULE()?`

**Comment by faceyspacey** [comment]
anyway, this would be a great package to get running again with React Native 0.20.0.

**Comment by catalinmiron** [comment]
I'll also use it if is going to work in react > 0.20. Are there any plans to upgrade it? 

__PS: I don't have Obj-C knowledge and I cannot update it properly__

**Comment by dzannotti** [comment]
Will make a new RN 0.22 compatible release in a few days

**Comment by dzannotti** [comment]
@catalinmiron @faceyspacey i apologise for the slow reply, I have just released a pure JS implementation of FB and AirBnB style and published it on npm i hope this fits your needs
